### ISSUE TITLE
Revert TileDB-GO branch after next libtiledb release

### ISSUE THREAD

**Issue by jdblischak** [jdblischak/centralized-tiledb-nightlies#7]
Once the next libtiledb is released and https://github.com/TileDB-Inc/TileDB-Go/pull/313 has been merged, undo https://github.com/jdblischak/centralized-tiledb-nightlies/commit/be2ce9603c7a88434e62316f5f66941c71c0c187 to revert to the master branch.

xref: https://github.com/TileDB-Inc/TileDB-Go/pull/312, https://github.com/TileDB-Inc/TileDB-Go/pull/314

**Comment by jdblischak** [comment]
Also need to revert https://github.com/jdblischak/centralized-tiledb-nightlies/commit/f08d905cb9cebb5124a00b5dd909c92d0d2ec8d3

**Comment by jdblischak** [comment]
The PR for the next release is https://github.com/TileDB-Inc/TileDB-Go/pull/319

**Comment by NullHypothesis** [comment]
Hey @jdblischak, I just released [v0.30.0](https://github.com/TileDB-Inc/TileDB-Go/releases/tag/v0.30.0).

**Comment by jdblischak** [comment]
Thanks @NullHypothesis!
